name: Android CI/CD

on: [push, pull_request]
  branches:
  - master
  - development
  - /^release-[0-9].[0-9].[0-9](-(alpha|beta))?$/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build
      run: ./gradlew cleanBuildCache clean build
    - name: test
      run: ./gradlew testDebugUnitTest
    - name: deploy
      if: github.event_name == 'push'
      branches:
      - master
      run: ./gradlew :cameraViewEx:install :cameraViewEx:bintrayUpload
